FROM centos:6

# Install Ansible
RUN yum groupinstall -y "development tools"
RUN yum -y install epel-release git sudo ansible

# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Install Ansible inventory file
RUN if [ ! -d "/etc/ansible" ]; then mkdir /etc/ansible; fi
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/sbin/init"]
